[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
async-await = "0.2.1"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
warp = "0.3.7"
